#!/bin/zsh
# Compile and package Sundial.app
#
#   ./build.sh              for debugging on this machine (arm64 only, ad-hoc signature, installed to the Desktop)
#   ./build.sh release      for release (universal binary + Developer ID signature + notarisation)
#
# Before releasing you first need to store the notarisation credentials (once only; you type
# the password yourself, it never goes through this script):
#   xcrun notarytool store-credentials solaris-notary \
#       --apple-id <your Apple ID> --team-id <TeamID> --password <app-specific password>

set -e
cd "$(dirname "$0")"

APP_NAME="Sundial"
# The single source of truth for the version number is the VERSION file at the repo root;
# both platforms read it from there.
# Info.plist and the csproj each used to carry their own copy, and changing one and
# forgetting the other was only a matter of time
VERSION="$(cat "$(dirname "$0")/../VERSION" 2>/dev/null || echo 0.0.0)"
BUNDLE_ID="com.cams-nir.sundial"
MIN_MACOS="13.0"
NOTARY_PROFILE="solaris-notary"
MODE="${1:-debug}"
[[ "$MODE" == "share" ]] && UNIVERSAL=1 || UNIVERSAL=0

# main.swift must come last (Swift requires the entry file's top-level statements to be compiled last)
SRC=(${(f)"$(ls *.swift | grep -v '^main.swift$')"} main.swift)

# Compiling and signing always happen in a temporary directory, and **must not be done on
# the Desktop**.
# The Desktop has iCloud sync switched on (you can see com.apple.fileprovider.fpfs#P in the
# xattrs), and the file provider asynchronously re-stamps com.apple.FinderInfo onto the .app,
# racing codesign —
# so codesign intermittently reports "resource fork, Finder information ... not allowed",
# and no amount of clearing the xattrs helps, because it gets added back after you have
# cleared it.
# The build products all land under the repo root rather than a hard-coded ~/Desktop/Sundial —
# wherever someone clones the repo, that is where the products turn up; hard-coding the path
# would not only mean they cannot be found, it could also overwrite a directory of the same
# name on someone else's Desktop
REPO="$(cd "$(dirname "$0")/.." && pwd)"

# Package it into a zip. The extended attributes must be stripped before ditto runs:
# from macOS 15 onwards every file gets a com.apple.provenance attribute, and `ditto -c -k`
# encodes extended attributes as AppleDouble files (._Contents, ._Info.plist and the like)
# and stuffs them into the zip as well. When someone unpacks it with unzip, those ._* files
# land inside the .app and the seal breaks then and there — codesign reports
# "a sealed resource is missing or invalid", and an app whose signature is broken simply
# will not open at all on recent macOS; even "Open Anyway" cannot rescue it.
# --norsrc --noextattr is the second line of defence. Stripping the attributes comes after
# signing: the signature lives in the Mach-O and in _CodeSignature, not in the extended
# attributes, so stripping them does not affect the seal (verified below)
zip_app() {
  xattr -cr "$1"
  ditto -c -k --keepParent --norsrc --noextattr "$1" "$2"
  # This verification step is not optional: unpack the zip again and re-verify the signature;
  # only once that passes is the package really fit to ship
  local t="$(mktemp -d)"
  ditto -x -k "$2" "$t"
  if ! codesign --verify --deep --strict "$t/$(basename "$1")" 2>/dev/null; then
    echo "✗ 解压后签名失效，包不能发。检查 zip 里有没有 ._* 残留：" >&2
    unzip -l "$2" | grep '\._\|__MACOSX' >&2
    rm -rf "$t"; exit 1
  fi
  rm -rf "$t"
}
BUILD="${TMPDIR:-/tmp}/sundial-build"
rm -rf "$BUILD" && mkdir -p "$BUILD"

if [[ "$MODE" == "release" || "$MODE" == "share" ]]; then
  echo "编译通用二进制（arm64 + x86_64，最低 macOS $MIN_MACOS）..."
  swiftc -O -swift-version 5 -target arm64-apple-macos$MIN_MACOS \
         -o "$BUILD/$APP_NAME-arm64" "${SRC[@]}"
  swiftc -O -swift-version 5 -target x86_64-apple-macos$MIN_MACOS \
         -o "$BUILD/$APP_NAME-x86_64" "${SRC[@]}"
  lipo -create -output "$BUILD/$APP_NAME" \
       "$BUILD/$APP_NAME-arm64" "$BUILD/$APP_NAME-x86_64"
  DEST=""
else
  echo "编译中（${#SRC[@]} 个源文件，仅本机架构）..."
  swiftc -O -swift-version 5 -target arm64-apple-macos$MIN_MACOS \
         -o "$BUILD/$APP_NAME" "${SRC[@]}"
  DEST="$REPO/$APP_NAME.app"
fi
APP="$BUILD/$APP_NAME.app"      # assembly and signing both happen here; once signed it is moved to the Desktop

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp Info.plist "$APP/Contents/Info.plist"
/usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $VERSION" \
                        "$APP/Contents/Info.plist" >/dev/null
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $VERSION" \
                        "$APP/Contents/Info.plist" >/dev/null
cp "$BUILD/$APP_NAME" "$APP/Contents/MacOS/$APP_NAME"
# Icon (generated by 图标生成器.swift — if you change the sun you have to run that script again)
# Sundial.icns is "whichever one is currently enabled"; it is produced by icon/make-icons.sh
# and is not checked in. On a fresh clone it does not exist, so fall back to the light version
ICON="$APP_NAME.icns"
[[ -f "$ICON" ]] || ICON="$APP_NAME-light.icns"
cp "$ICON" "$APP/Contents/Resources/$APP_NAME.icns"
# Clear the extended attributes: cp brings the source file's xattrs along with it
# (.icns files often carry Finder information).
# Note that com.apple.provenance cannot be cleared, but codesign does not mind that one —
# the one it minds is FinderInfo
clean_xattr() { xattr -cr "$1" 2>/dev/null || true; }
clean_xattr "$APP"

if [[ "$MODE" == "release" ]]; then
  ID=$(security find-identity -v -p codesigning | grep "Developer ID Application" | head -1 \
       | sed -E 's/.*"(.*)"/\1/')
  if [[ -z "$ID" ]]; then
    echo "✗ 钥匙串里没有 Developer ID Application 证书。"
    echo "  请先在 Xcode › Settings › Accounts 里下载，或到 developer.apple.com 创建。"
    exit 1
  fi
  echo "签名：$ID"
  # runtime = hardened runtime, a hard requirement for notarisation
  clean_xattr "$APP"
  codesign --force --options runtime --timestamp \
           --identifier "$BUNDLE_ID" --sign "$ID" "$APP"

  ZIP="$BUILD/$APP_NAME.zip"
  zip_app "$APP" "$ZIP"
  echo "提交公证（几十秒到几分钟）..."
  xcrun notarytool submit "$ZIP" --keychain-profile "$NOTARY_PROFILE" --wait
  xcrun stapler staple "$APP"         # staple the notarisation ticket into the app so it verifies offline too

  rm -f "$ZIP"
  OUT="$REPO/dist/$APP_NAME.zip"
  zip_app "$APP" "$OUT"
  echo "✓ 可分发文件：$OUT"
  spctl -a -vv "$APP" 2>&1 | tail -2
elif [[ "$MODE" == "debug" ]]; then
  clean_xattr "$APP"
  codesign --force --sign - "$APP"
  # Move it to the Desktop only after signing: whatever iCloud stamps on it afterwards cannot
  # affect the signature that is already embedded inside
  rm -rf "$DEST" && ditto "$APP" "$DEST"
  echo "完成：$DEST"
fi

# share mode: universal binary + ad-hoc signature + packaging, for when you have no developer account
if [[ "$MODE" == "share" ]]; then
  clean_xattr "$APP"
  codesign --force --sign - "$APP"
  OUT="$REPO/dist/$APP_NAME.zip"
  rm -f "$OUT"
  zip_app "$APP" "$OUT"
  echo "✓ 可分发文件：$OUT（首次打开需去隔离，见 dist/INSTALL.txt）"
fi
